motion_action_node:
  ros__parameters:
    relocation_topic: /odin1/relocation
    velocity_topic: /t0x0101_pid
    control_frequency_hz: 20.0
    initial_pose_timeout_sec: 2.0
    yaw_timeout_sec: 5.0
    xy_timeout_sec: 5.0
    brake_duration_sec: 0.1
    brake_frequency_hz: 20.0

    yaw_tolerance_deg: 1.0
    position_tolerance: 0.015

    max_linear_speed: 0.8
    max_angular_speed: 0.8
    min_linear_speed: 0.18
    min_angular_speed: 0.18
    integral_limit: 0.5

    yaw_pid:
      kp: 1.2
      ki: 0.0
      kd: 0.05
    x_pid:
      kp: 0.8
      ki: 0.0
      kd: 0.0
    y_pid:
      kp: 0.8
      ki: 0.0
      kd: 0.0
